name: build

on: [ push , pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Pyhon
        uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'
          architecture: x64
      - name: Installing dependencies
        run: |
          python -m venv apps
          apps/bin/activate
          pip install -r requirePackage.txt
          pip install pyinstaller
          pyinstaller ./bot.py -F
      - name: upload
        uses: actions/upload-artifact@v3
        with: 
          name: bot
          path: dist/*
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Pyhon
        uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'
          architecture: x64
      - name: Installing dependencies
        run: |
          python -m venv apps
          apps/bin/activate
          pip install -r requirePackage.txt
          pip install pyinstaller
          pyinstaller ./bot.py -F
      - name: upload
        uses: actions/upload-artifact@v3
        with: 
          name: bot
          path: dist/*
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Pyhon
        uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'
          architecture: x64
      - name: Installing dependencies
        run: |
          python -m venv apps
          apps/bin/activate
          pip install -r requirePackage.txt
          pip install pyinstaller
          pyinstaller ./bot.py -F
      - name: upload
        uses: actions/upload-artifact@v3
        with: 
          name: bot
          path: dist/*